name: Valeria D'Amico
shortname: Valeria
pygments: true
nav:
  - title: Biography
    url: /bio.html
  - title: Projects
    url: /projects.html
  - title: GyrotonicÂ®
    url: /gyrotonic.html
  - title: Agenda
    url: /agenda.html
